### ISSUE TITLE
Last test times out on travis and locally

### ISSUE THREAD

**Issue by defvol** [mapbox/tile-decorator#3]
https://travis-ci.org/mapbox/tile-decorator

**Comment by mourner** [comment]
Found the issue — my latest commit https://github.com/mapbox/tile-decorator/commit/f946416ea5b80e75555733280d74833e3616232e changed the output of the test tile a little, but `tap` is notoriously slow when it tries to output big JSON diffs — the diff here is slow enough to make it freeze. As a solution, I'm going to 1) update the pbf fixture, 2) switch from tap to tape.

My mistake — I don't know why I committed this to master without making sure the tests work.

**Comment by defvol** [comment]
🤔 interesting finding, so... a slow diff
👍 for tape over tap

Thanks for taking the time to fix this. I'll rebase my other PRs.
